### ISSUE TITLE
Consider replasing Mersenne twister (or adding better choise)

### ISSUE THREAD

**Issue by TommiPrami** [Xor-el/DelphiIntXLib#1]
http://www.pcg-random.org/

just stumbled upon this, and it should be quite a lot better than Mersenne Twister.

-Tee-

**Comment by Xor-el** [comment]
Hello, 
Thanks for your Suggestion but I don't think replacing Mersenne twister would cut it. my reason being that it has undergone a lot of Scrutiny to be used as the default PRNG in various systems unlike PCG.
I might add PCG later but not as the default random number generator.
if you feel a strong reason to disprove this, you could open up another issue.
Regards.

**Comment by TommiPrami** [comment]
If you have some spare time, watch this : https://www.youtube.com/watch?v=45Oet5qjlms 

My conclusion was that even the Mersenne Twister is in many places the default random number generator, that does not mean it should be :)

**Comment by TommiPrami** [comment]
But in other hand it is your choice which algorithm you'll like to use

**Comment by Xor-el** [comment]
Thanks a lot for the video.
will have a look at it when I have some time.
Regards.

**Comment by Xor-el** [comment]
Hello, after some tests, I finally decided to use Pcg Random as the default random number generator.
I just pushed the Update.
Thanks a lot for your Suggestion. 
Regards.
